rootProject.name = 'silver-soul-curiosity'

include 'libs'

file('services').eachDir { dir ->
    include dir.name
    project(":${dir.name}").projectDir = dir

    def buildFile = file("${dir.absolutePath}/build.gradle")
    if (!buildFile.exists()) {
        buildFile.text = """\
plugins {
    id 'java'
    id 'io.spring.dependency-management'
}

description = '${dir.name} module'
""".stripIndent()
    }
}